services:
  frontend:
    image: !reset null
    build:
      context: ./frontend/
      dockerfile: Dockerfile

  backend:
    image: !reset null
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        VERSION: 1.0.0

  backend-report:
    image: !reset null
    build:
      context: ./backend-report/
      dockerfile: Dockerfile