apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  annotations:
    helm.sh/hook-weight: "-5"
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: postgresql-conf
          ports:
            - containerPort: {{ .Values.postgresql.containerPort }}
          resources:
{{ toYaml .Values.postgresql.resources | indent 12 }}
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgresql.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
  annotations:
    helm.sh/hook-weight: "-5"
spec:
  ports:
    - port: {{ .Values.postgresql.containerPort }}
      targetPort: {{ .Values.postgresql.containerPort }}
  selector:
    app: postgresql
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-conf
  annotations:
    helm.sh/hook-weight: "-5"
data:
  POSTGRES_USER: {{ .Values.postgresql.env.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.env.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.postgresql.env.POSTGRES_DB | quote }}
