CREATE TABLE IF NOT EXISTS product (
	id BIGINT generated by default as identity,
	name VARCHAR(255),
	picture_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS product_info (
	product_id BIGINT,
	name VARCHAR(255),
	price DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS orders (
	id BIGINT generated by default as identity,	
	status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS orders_date (
	order_id BIGINT,
	status VARCHAR(255),
	date_created DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS order_product (
	quantity INT,
	order_id BIGINT,
	product_id BIGINT
);